name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        queries: security-and-quality
        build-mode: none
        
    # Build mode 'none' tells CodeQL to analyze source without building
    # This is appropriate for Unreal Engine plugins without UE5.5 installed in CI
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:cpp"

  plugin-validation:
    name: Plugin Manifest Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: Validate plugin manifest
      run: |
        # Check if uplugin file is valid JSON
        if ! jq empty ChatGPTEditor.uplugin; then
          echo "Error: ChatGPTEditor.uplugin is not valid JSON"
          exit 1
        fi
        
        # Check required fields
        VERSION=$(jq -r '.Version' ChatGPTEditor.uplugin)
        VERSION_NAME=$(jq -r '.VersionName' ChatGPTEditor.uplugin)
        FRIENDLY_NAME=$(jq -r '.FriendlyName' ChatGPTEditor.uplugin)
        
        echo "Plugin Version: $VERSION"
        echo "Plugin Version Name: $VERSION_NAME"
        echo "Plugin Friendly Name: $FRIENDLY_NAME"
        
        if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
          echo "Error: Version field is missing or empty"
          exit 1
        fi
