name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get version from tag
      id: get_version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from commits since last tag
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s" --no-merges)
        else
          CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s" --no-merges)
        fi
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release Archive
      run: |
        # Create a clean release archive
        mkdir -p release
        cp -r Source release/
        cp ChatGPTEditor.uplugin release/
        cp README.md release/
        cp LICENSE release/ 2>/dev/null || true
        cd release
        zip -r ../ChatGPTEditor-v${{ steps.get_version.outputs.VERSION }}.zip .
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ChatGPTEditor v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changes in this Release
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          1. Download the release archive
          2. Extract to your project's Plugins folder
          3. Follow the installation instructions in README.md
          
          ## Requirements
          
          - Unreal Engine 5.5 or later
          - Valid OpenAI API key
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ChatGPTEditor-v${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: ChatGPTEditor-v${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

  update-marketplace:
    name: Notify Marketplace Update
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: read
    
    steps:
    - name: Placeholder for Marketplace Update
      run: |
        echo "In production, this job would update the Unreal Engine Marketplace listing"
        echo "This requires additional Epic Games integration"
